name: Duplicate Issue Searcher

on:
  issues:
    types: [opened, edited]

jobs:
  similarity-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: analysis
        uses: happygirlzt/duplicate-issue-searcher@c39f4252797222d4456d464aa48539681d5138fc
        with:
          filter-threshold: 0.5
          title-excludes: 'bug, not, 1234'
          comment-title: '### Potential duplicates'
          comment-body: '${index}. ${similarity} #${number}'
