name: Issues Similarity Analysis

on:
  issues:
    types: [opened, edited]

jobs:
  similarity-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: analysis
        uses: happygirlzt/issues-similarity-analysis@5031b74d6097ba8b1b3127583e160cb98abfe0b3
        with:
          filter-threshold: 0.5
          title-excludes: 'bug, not, 1234'
          comment-title: '### See'
          comment-body: '${index}. ${similarity} #${number}'
