name: Duplicate Issue Searcher

on:
  issues:
    types: [opened, edited]

jobs:
  similarity-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: analysis
        uses: happygirlzt/duplicate-issue-searcher@6775df1fa50b395c2387e71f2c78d1e39ffe699a
        with:
          filter-threshold: 0.5
          comment-title: '### Potential duplicates'
          comment-body: '${index}. ${similarity} #${number}'
